version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nano_ugin
      - POSTGRES_USER=nano_user
      - POSTGRES_PASSWORD=nano_password


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app/nano_ugin
    ports:
      - "4545:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://nano_user:nano_password@db:5432/nano_ugin
      - DEBUG=True

volumes:
  postgres_data:
