# Generated by Django 4.2.7 on 2025-11-18 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название параметра')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Ключ параметра')),
                ('parameter_type', models.CharField(choices=[('text', 'Текст'), ('integer', 'Целое число'), ('float', 'Дробное число'), ('boolean', 'Да/Нет'), ('date', 'Дата'), ('datetime', 'Дата и время')], default='text', max_length=20, verbose_name='Тип параметра')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('device_types', models.ManyToManyField(related_name='parameters', to='equipment.devicetype', verbose_name='Типы устройств')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='equipment.devicetype', verbose_name='Тип устройства')),
            ],
            options={
                'verbose_name': 'Модель устройства',
                'verbose_name_plural': 'Модели устройств',
                'unique_together': {('name', 'device_type')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название устройства')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('online', 'На сети'), ('offline', 'Не на сети')], default='online', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='equipment.devicemodel', verbose_name='Модель устройства')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='equipment.device')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='equipment.parameter')),
            ],
            options={
                'verbose_name': 'Значение параметра',
                'verbose_name_plural': 'Значения параметров',
                'unique_together': {('device', 'parameter')},
            },
        ),
    ]
