# Generated by Django 4.2.7 on 2025-11-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='device_types',
            field=models.ManyToManyField(blank=True, related_name='parameters', to='equipment.devicetype', verbose_name='Типы устройств'),
        ),
    ]
